spring:
  application:
    name: AgentX
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agenthub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

server:
  port: 8080
  servlet:
    context-path: /api

# LLM服务配置
llm:
  provider:
    default: ${LLM_DEFAULT_PROVIDER:siliconflow}
    providers:
      siliconflow:
        name: SiliconFlow
        api-url: ${SILICONFLOW_API_URL:https://api.siliconflow.cn/v1/chat/completions}
        api-key: ${SILICONFLOW_API_KEY:}
        model: ${SILICONFLOW_MODEL:Qwen/Qwen3-32B}
        timeout: ${SILICONFLOW_TIMEOUT:30000}


# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xiaoguai.agentx.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    type-handlers-package: com.xiaoguai.agentx.infrastrcture.converter
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

# 邮箱参数
mail:
  smtp:
    host: ${MAIL_SMTP_HOST:smtp.qq.com}
    port: ${MAIL_SMTP_PORT:25}
    username: ${MAIL_SMTP_USERNAME:xx}
    password: ${MAIL_SMTP_PASSWORD:xx}
  verification:
    template: ${MAIL_VERIFICATION_TEMPLATE:您的验证码是:%s，有效期10分钟，请勿泄露给他人。}
    subject: ${MAIL_VERIFICATION_SUBJECT:AgenHub - 邮箱验证码}


logging:
  level:
    org.springframework.web: DEBUG



s3:
  provider: aliyun # 服务提供商
  aliyun:
    endpoint: ${S3_ALIYUN_ENDPOINT}
    access-key: ${S3_ALIYUN_ACCESS_KEY}
    secret-key: ${S3_ALIYUN_SECRET_KEY}
    bucket-name: ${S3_ALIYUN_BUCKET_NAME}
    region: ${S3_ALIYUN_REGION}